Add support for one string arm image
microsoft/lisa pull request #1068
Opened 2020-10-23 10:22 UTC by lubaihua33

Run the command:
```
poetry run python lisa/main.py -d -r ..\runbook\smoke.yml -v adminPrivateKeyFile:"id_rsa" -v gGallery:"Canonical UbuntuServer 18.04-LTS Latest"
```
Test result is:
```
2020-10-23 08:06:40.974 [INFO] LISA.runner ________________________________________
2020-10-23 08:06:40.976 [INFO] LISA.runner                            Provisioning.smoke_test: PASSED
2020-10-23 08:06:40.978 [INFO] LISA.runner   TOTAL      : 1
2020-10-23 08:06:40.979 [INFO] LISA.runner     NOTRUN   : 0
2020-10-23 08:06:40.979 [INFO] LISA.runner     RUNNING  : 0
2020-10-23 08:06:40.981 [INFO] LISA.runner     FAILED   : 0
2020-10-23 08:06:40.981 [INFO] LISA.runner     PASSED   : 1
2020-10-23 08:06:40.983 [INFO] LISA.runner     SKIPPED  : 0
2020-10-23 08:06:40.984 [DEBUG] LISA.Action LisaRunner status changed from RUNNING to SUCCESS with 555.069 sec
2020-10-23 08:06:40.987 [INFO] LISA completed in 609.971 sec
```

2020-10-23 10:24 UTC, squirrelsc commented
It's better not to close a PR. It makes comments on previous PR out of track.

2020-10-24 13:56 UTC, squirrelsc requested changes

2020-10-24 13:56 UTC, squirrelsc commented on lisa/sut_orchestrator/azure/platform_.py
> +            gallery = self.gallery.strip(" :,").split()
not add `,`

2020-10-24 13:56 UTC, squirrelsc commented on lisa/sut_orchestrator/azure/platform_.py
> +                    f"Invalid value for the provided gallery "
Mention colon `:` also supports

2020-10-26 04:31 UTC, lubaihua33 commented on lisa/sut_orchestrator/azure/platform_.py
> +            gallery = self.gallery.strip(" :,").split()
I 

> It's better not to close a PR. It makes comments on previous PR out of track.

Sure.

2020-10-26 06:19 UTC, squirrelsc submitted a review, later dismissed

2020-10-26 14:11 UTC, squirrelsc approved these changes

2020-10-27 01:48 UTC, merged