Collect image, size, location and platform info when deploy failed.
microsoft/lisa pull request #1090
Opened 2020-11-05 06:55 UTC by LiliDeng

Even deploy fail, we still need collect as much info as we can.

2020-11-05 07:19 UTC, squirrelsc approved these changes

2020-11-06 00:28 UTC, squirrelsc commented on lisa/node.py
> +        self.is_ready: bool = False
Change it's name from `is_ready` to `is_connected` to make it more accurate and same as new environment status.

2020-11-06 00:30 UTC, squirrelsc commented on lisa/node.py
> +        self.is_ready: bool = False
And reset it to False in `close`.

2020-11-06 00:31 UTC, squirrelsc requested changes
Provided some missed comments

2020-11-06 05:40 UTC, squirrelsc reviewed
Merge latest commits to previous, because it handles same things in this PR.

2020-11-06 05:47 UTC, LiliDeng commented
> Merge latest commits to previous, because it handles same things in this PR.

Done.

2020-11-06 05:52 UTC, squirrelsc approved these changes

2020-11-06 07:36 UTC, merged