LISAv2: implement supported vm size feature
microsoft/lisa pull request #122
Opened 2019-04-15 23:17 UTC by ader1990

Implemented feature request: https://github.com/LIS/LISAv2/issues/108

Example run:

```
# This run will use 3 VM sizes and force the framework to accept those vm sizes, even if in the XML definition for the TC, there is a SupportedVMSize tag containing "one"
.\Run-LisaV2.ps1 -TestPlatform HyperV -RGIdentifier "ader1990" -OsVHD "test.vhdx" -TestNames 'BVT-IS-ROOT-PASSWORD-DELETED' -OverrideVMSize "one,two" -CustomParameters "SupportedVmSi
ze=one,two"
```

2019-04-15 23:48 UTC, ader1990 commented
Execution tested with multiple values.

This is one of the most complex run:

```
.\Run-LisaV2.ps1 -TestPlatform HyperV -RGIdentifier "ader1990" -TestNames 'BVT-CORE-TIMESYNC-NTP' -OverrideVMSize "one1,two2" -CustomParameters "SupportedVmSize=one*,two*,three"

04/15/2019 23:46:49 : [INFO ] Collected Test: BVT-CORE-TIMESYNC-NTP
04/15/2019 23:46:49 : [INFO ] 1 Test Cases have been collected
04/15/2019 23:46:49 : [INFO ] The OverrideVMSize of case BVT-CORE-TIMESYNC-NTP is set to one1,two2
```

2019-04-16 00:48 UTC, juhlee-microsoft requested changes

2019-04-16 00:48 UTC, juhlee-microsoft commented on XML/TestCases/FunctionalTests-DPDK.xml
> +        <SupportedVmSize>Standard_D*</SupportedVmSize>
DPDK supports regardless size, right? if that is true, we can not put this tag here.

2019-04-16 00:48 UTC, juhlee-microsoft commented on Libraries/CommonFunctions.psm1
> +			if (!($TestCategory.Split(",").Contains($test.Category)) -and ($TestCategory -ne "*")) {
what does it mean? how does this condition work? true vs. false??

2019-04-16 17:59 UTC, ader1990 commented
Closing PR, as it is not needed.

2019-04-16 17:59 UTC, closed without merging