Add workaround for expired RHUI client certificate issue on old RHEL VM image.
microsoft/lisa pull request #1245
Opened 2021-03-24 14:41 UTC by LiliDeng

2021-03-24 14:52 UTC, squirrelsc requested changes

2021-03-24 14:52 UTC, squirrelsc commented on lisa/operating_system.py
> +    #  RedHat RHEL 8 8.0.2019050711
Did we file bug for this? If so, let's keep it failed, until it's clear.

2021-03-24 23:26 UTC, glima commented on lisa/operating_system.py
> +        #  /redhat-rhui#azure-rhui-infrastructure
Would you please leave the URL as a single line?

2021-03-25 06:02 UTC, squirrelsc approved these changes

2021-03-25 06:58 UTC, merged