DPDK ring_ping: change metric
microsoft/lisa pull request #2143
Opened 2022-07-19 20:36 UTC by kamalca

For increased test reliability, we decided to reduce the bar for ring ping performance. Further discussion may need to occur surrounding the performance expectations of this bug.

2022-07-19 21:19 UTC, mcgov requested changes
Can we refactor the guts of the verify_dpdk_ring_ping logic into dpdkutil as well, leaving the performance check as the last thing to check in the test suite. This will prep for adding the stricter perf version.

2022-07-19 21:19 UTC, mcgov commented on microsoft/testsuites/dpdk/dpdksuite.py
>      # grabbing the max latency of 99.999% of data in nanoseconds.
This comment needs adjusting to explain the change.

2022-07-26 01:53 UTC, LiliDeng commented
any update? @kamalca

2022-08-16 05:22 UTC, LiliDeng approved these changes

2022-08-16 17:09 UTC, mcgov approved these changes

2022-08-16 17:09 UTC, merged