Fix test case issues for python detect and NESTED-KVM-BASIC-VERIFICATION
microsoft/lisa pull request #248
Opened 2019-05-23 08:01 UTC by LiliDeng

canonical ubuntuserver 18.04-lts Latest 
credativ Debian 9-backports Latest
RedHat RHEL 7.5 Latest
OpenLogic CentOS 7.6 Latest
Oracle Oracle-Linux 7.6 Latest
SUSE SLES 15 Latest
**WALA-VERIFY-HOSTNAME PASS,NESTED-KVM-BASIC-VERIFICATION PASS**

CoreOS CoreOS Stable Latest 
clear-linux-project clear-linux-os basic latest
RedHat RHEL 8 8.0.2019050711
**WALA-VERIFY-HOSTNAME PASS**

RedHat RHEL 8 8.0.2019050711
**NESTED-KVM-BASIC-VERIFICATION Fail, file an issue for this**

2019-05-23 12:01 UTC, chvalean requested changes

2019-05-23 12:01 UTC, chvalean commented on Testscripts/Linux/utils.sh
> +			install_package "gcc make wget"
this has to be moved right after the echo above - line 2360.
you already have a wget command above this install_package, so the order is off.

and while at it, please remove the verbose flag from tar extract.

2019-05-23 19:29 UTC, lizzha approved these changes

2019-05-24 07:00 UTC, chvalean approved these changes

2019-05-24 07:00 UTC, merged