ETHTOOL-CHECK-STATISTICS supports test for centos
microsoft/lisa pull request #254
Opened 2019-05-24 08:31 UTC by xian123

1. The ~ is equal to root not /home/TESTUSER expected on Centos once the script is excueted with **sudo**. In order to support more distros,  an explicit path is defined to replace ~. 
2. Split long lines into short ones.
3. Install dependencies

2019-05-24 08:44 UTC, xian123 commented
Test results against ubuntu and centos:
```
[LISAv2 Test Results Summary]
Test Run On           : 05/24/2019 06:43:34
VHD Under Test        : D:\xhx\vhds\Centos_7.5.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:16
   ID TestArea             TestCaseName                                                     TestResult TestDuration(in minutes)
------------------------------------------------------------------------------------------------------------------
    1 NETWORK              ETHTOOL-CHECK-STATISTICS                                PASS                10.99

[LISAv2 Test Results Summary]
Test Run On           : 05/24/2019 07:42:16
VHD Under Test        : D:\xhx\vhds\Ubuntu_18.04.1.vhdx
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:25
   ID TestArea             TestCaseName                                                TestResult TestDuration(in minutes) 
------------------------------------------------------------------------------------------------------------------
    1 NETWORK              ETHTOOL-CHECK-STATISTICS                                   PASS                 20.1 
```

2019-05-24 08:47 UTC, LiliDeng requested changes

2019-05-24 08:47 UTC, LiliDeng commented on Testscripts/Linux/Ethtool-Check-Statistics.sh
> +if [ $remote_user == "root" ]; then
[[ $remote_user == "root" ]]

2019-05-24 08:47 UTC, LiliDeng commented on Testscripts/Linux/Ethtool-Check-Statistics.sh
> +if [ $remote_user == "root" ]; then
it always equals root here?

2019-05-27 10:27 UTC, chvalean approved these changes

2019-05-27 13:12 UTC, LiliDeng approved these changes

2019-05-27 13:26 UTC, merged