Fix issues for sle_hpc distro
microsoft/lisa pull request #319
Opened 2019-06-12 05:55 UTC by Tong-Xu

2019-06-12 06:49 UTC, juhlee-microsoft commented
Please add the description and test result

2019-06-12 08:18 UTC, chvalean requested changes

2019-06-12 08:18 UTC, chvalean commented on Testscripts/Linux/DetectLinuxDistro.sh
> +                elif [[ "$tmp" =~ "SUSE Linux Enterprise High Performance Computing 15 SP1" ]]; then
can you make this more generic, like "SUSE Linux Enterprise High Performance Computing"?
That way we might catch any HPC images in the future, and not be hardcoded to v15 SP1.

2019-06-12 09:41 UTC, LiliDeng commented
Test results 
```
[LISAv2 Test Results Summary]
Test Run On           : 06/12/2019 06:03:09
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/suse-sles-15-sp1-hpc-v20190603.vhd
Total Test Cases      : 4 (3 Passed, 1 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:42

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LIS-MODULES-CHECK                                                                 PASS                 2.25 
    2 CORE                 VERIFY-LIS-MODULES-VERSION                                                        PASS                 1.93 
    3 CPU                  PERF-SYSCALL-BENCHMARK                                                            PASS                 8.15 
	test=bench_00_null_call_regs : AverageReal=0.026 AverageUser=0.025 AverageSystem=0.000 : Completed 
	test=bench_01_null_call_stack : AverageReal=0.028 AverageUser=0.028 AverageSystem=0.000 : Completed 
	test=bench_02_getpid_syscall : AverageReal=5.305 AverageUser=3.636 AverageSystem=1.669 : Completed 
	test=bench_03_getpid_vdso : AverageReal=5.382 AverageUser=3.707 AverageSystem=1.675 : Completed 
	test=bench_10_read_syscall : AverageReal=0.645 AverageUser=0.365 AverageSystem=0.280 : Completed 
	test=bench_11_read_vdso : AverageReal=0.660 AverageUser=0.384 AverageSystem=0.277 : Completed 
	test=bench_12_read_stdio : AverageReal=0.021 AverageUser=0.020 AverageSystem=0.001 : Completed 
	test=bench_20_write_syscall : AverageReal=0.608 AverageUser=0.378 AverageSystem=0.230 : Completed 
	test=bench_21_write_vdso : AverageReal=0.621 AverageUser=0.390 AverageSystem=0.231 : Completed 
	test=bench_22_write_stdio : AverageReal=0.024 AverageUser=0.023 AverageSystem=0.001 : Completed 

[LISAv2 Test Results Summary]
Test Run On           : 06/12/2019 06:51:08
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/suse-sles-15-sp1-hpc-v20190603.vhd
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:8

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NESTED               NESTED-KVM-BASIC-VERIFICATION                                                     PASS                 5.24 


[LISAv2 Test Results Summary]
Test Run On           : 06/12/2019 07:01:41
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Total Test Cases      : 4 (4 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:29

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LIS-MODULES-CHECK                                                                 PASS                 2.39 
    2 CORE                 VERIFY-LIS-MODULES-VERSION                                                        PASS                  2.2 
    3 CPU                  PERF-SYSCALL-BENCHMARK                                                            PASS                 8.26 
	test=bench_00_null_call_regs : AverageReal=0.026 AverageUser=0.026 AverageSystem=0.000 : Completed 
	test=bench_01_null_call_stack : AverageReal=0.034 AverageUser=0.034 AverageSystem=0.000 : Completed 
	test=bench_02_getpid_syscall : AverageReal=4.808 AverageUser=3.342 AverageSystem=1.466 : Completed 
	test=bench_03_getpid_vdso : AverageReal=4.851 AverageUser=3.380 AverageSystem=1.471 : Completed 
	test=bench_10_read_syscall : AverageReal=0.605 AverageUser=0.363 AverageSystem=0.242 : Completed 
	test=bench_11_read_vdso : AverageReal=0.620 AverageUser=0.322 AverageSystem=0.298 : Completed 
	test=bench_12_read_stdio : AverageReal=0.020 AverageUser=0.019 AverageSystem=0.001 : Completed 
	test=bench_20_write_syscall : AverageReal=0.572 AverageUser=0.333 AverageSystem=0.239 : Completed 
	test=bench_21_write_vdso : AverageReal=0.555 AverageUser=0.332 AverageSystem=0.223 : Completed 
	test=bench_22_write_stdio : AverageReal=0.023 AverageUser=0.021 AverageSystem=0.001 : Completed 
    4 NESTED               NESTED-KVM-BASIC-VERIFICATION                                                     PASS                 7.29 
```

2019-06-12 09:48 UTC, chvalean commented on Testscripts/Linux/DetectLinuxDistro.sh
> +                elif [[ "$tmp" =~ "SUSE Linux Enterprise High Performance Computing 15 SP1" ]]; then
same edit here - https://github.com/LIS/LISAv2/pull/319/files#diff-2411aaddd5536a1d954db78a819c3f6fR1848
don't know why it won't let me comment on that line

2019-06-12 10:18 UTC, chvalean approved these changes

2019-06-12 19:30 UTC, juhlee-microsoft requested changes

2019-06-12 19:30 UTC, juhlee-microsoft commented on Testscripts/Linux/VERIFY-LIS-MODULES-VERSION.sh
> +vmbus_included=$(grep CONFIG_HYPERV=y "$config_path")
Below 7 if-statement blocks can be in a for-loop statement.

2019-06-14 00:41 UTC, juhlee-microsoft approved these changes

2019-06-14 00:41 UTC, merged