Reduce min data_disk_count to 4 in IO perf test.
microsoft/lisa pull request #3286
Opened 2024-04-30 08:31 UTC by SRIKKANTH

2024-05-06 13:57 UTC, LiliDeng commented
@johnsongeorge-w please review, thanks.

2024-05-07 15:52 UTC, johnsongeorge-w requested changes
Set the default for disk count and min iops as 16 and 5000 respectively.

2024-05-08 06:48 UTC, SRIKKANTH commented
> Set the default for disk count and min iops as 16 and 5000 respectively.
@johnsongeorge-w This is what the default in the test case which is blocking us the test from running on smaller tests. 
I am reducing the min disc count to 4 which is the minimum number of discs supported any azure VM SKU.

2024-05-08 16:54 UTC, johnsongeorge-w commented
> > Set the default for disk count and min iops as 16 and 5000 respectively.
> > @johnsongeorge-w This is what the default in the test case which is blocking us the test from running on smaller tests.
> > I am reducing the min disc count to 4 which is the minimum number of discs supported any azure VM SKU.

I'm talking about the defaults in runbook

2024-05-09 15:14 UTC, SRIKKANTH commented
> > > Set the default for disk count and min iops as 16 and 5000 respectively.
> > > @johnsongeorge-w This is what the default in the test case which is blocking us the test from running on smaller tests.
> > > I am reducing the min disc count to 4 which is the minimum number of discs supported any azure VM SKU.
> 
> I'm talking about the defaults in runbook
The default runbook ("runbook\partial\platform_azure.yml") has values data_disk_iops=0, data_disk_count=0. 
Changing these values will result in creation of each test VM with that config. 
I don't think its a good idea.

2024-07-04 08:40 UTC, closed without merging