NETWORK.ETHTOOL: Skip Get/Set msg level test if kernel symbols missing
microsoft/lisa pull request #366
Opened 2019-06-25 16:34 UTC by stefanlupsa

* check for get / set msg level symbols in the lib of the current kernel, if missing skip the test.
* if module is builtin check in /boot/System.map of the current kernel.

Fixes #341 
(Continued #363)

Canonical UbuntuServer 18.04-LTS 18.04.201906040
Kernel module, contains functionality: expected pass
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:18:25
[azure] ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : 18.04.201906040
[azure] Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:3
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                         PASS                 1.14 
```

Canonical UbuntuServer 16.04-LTS 16.04.201906050
Kernel module, does not contain functionality: expect skipped
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:18:16
[azure] ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : 16.04.201906050
[azure] Total Test Cases      : 1 (0 Passed, 0 Failed, 0 Aborted, 1 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:3
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                      SKIPPED                 0.69 
```

RedHat RHEL 7-RAW 7.6.2019062020
Archived kernel module, does not contain functionality: expect skipped
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:17:04
[azure] ARM Image Under Test  : RedHat : RHEL : 7-RAW : 7.6.2019062020
[azure] Total Test Cases      : 1 (0 Passed, 0 Failed, 0 Aborted, 1 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:3
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                      SKIPPED                 0.72 
```

SUSE SLES 15 2019.06.17
Kernel builtin, contains functionality, expect pass
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:16:10
[azure] ARM Image Under Test  : SUSE : SLES : 15 : 2019.06.17
[azure] Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:5
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                         PASS                  0.5 
```

2019-06-25 16:37 UTC, ader1990 requested changes

2019-06-25 16:37 UTC, ader1990 commented on Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh
> +if [ "$(grep -c netvsc < /lib/modules/"$kernel_version"/modules.builtin)" == 0 ]; then
reuse /lib/modules/ by putting in a variable

2019-06-25 16:37 UTC, ader1990 commented on Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh
> +    msg_level_symbols=$(grep 'netvsc.*msglevel' "/boot/System.map-$(uname -r)")
uname -r is kernel_version

2019-06-25 16:37 UTC, ader1990 commented on Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh
> +    UpdateSummary "Getting / Setting the driver message type flags from ethtool is not supported on $kernel_version, skipping test."
line too long, try to shrink the message to a more concise version

2019-06-25 17:39 UTC, chvalean commented on Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh
> +if ! which nm; then
move the check/install for nm in the if section below, only if netvsc is present as a module.

2019-06-26 09:37 UTC, ader1990 approved these changes

2019-06-26 09:37 UTC, merged