DPDK path not found by Lisav2 script fixed
microsoft/lisa pull request #514
Opened 2019-08-13 00:27 UTC by abhimarathe

Fixed DPDK path not found bug in lisav2 for .git and .tar source input.

2019-08-13 00:27 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/LIS/LISAv2?pullRequest=514) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/LIS/LISAv2?pullRequest=514) before we can accept your contribution.<br/><br/>:x: abhimarathe [sign now](https://cla.opensource.microsoft.com/LIS/LISAv2?pullRequest=514)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/LIS/LISAv2?pullRequest=514) it.</sub>

2019-08-13 05:59 UTC, juhlee-microsoft commented
Please post the local test result

2019-08-13 07:31 UTC, iamshital requested changes

2019-08-13 07:31 UTC, iamshital commented on Testscripts/Linux/dpdkSetupAndRunTest.sh
> + DPDK_DIR="dpdk"
Formatting issue.

2019-08-13 21:49 UTC, abhimarathe commented
[LISAv2 Test Results Summary]
Test Run On           : 08/13/2019 18:21:49
ARM Image Under Test  : Openlogic : CentOS : 7.5 : latest
Initial Kernel Version: 3.10.0-862.11.6.el7.x86_64
Final Kernel Version  : 3.10.0-862.11.6.el7.x86_64
Total Test Cases      : 6 (5 Passed, 0 Failed, 1 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:3:13

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                19.71 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
19.08.0-rc4  txonly    after   3132002       3132002      
19.08.0-rc4  txonly    before  3299190       3299190      
19.08.0-rc4  txonly    during  260212        260212       
19.08.0-rc4  txonly    overall 1848763       1848763 
    2 DPDK                 PERF-DPDK-FWD-PPS-DS15                                                            PASS                 15.8 
dpdk_version core tx_pps_avg fwdrx_pps_avg fwdtx_pps_avg rx_pps_avg
------------ ---- ---------- ------------- ------------- ----------
19.08.0-rc4  2    16158789   10488330      10488330      9957805   
19.08.0-rc4  4    16455757   10487332      10487332      10032969  
19.08.0-rc4  8    15954325   10489089      10489089      10190189 
    3 DPDK                 PERF-DPDK-SINGLE-CORE-PPS-DS4                                                  ABORTED                68.85 
    4 DPDK                 PERF-DPDK-MULTICORE-PPS-F32                                                       PASS                31.09 
dpdk_version test_mode core max_rx_pps tx_pps_avg rx_pps_avg fwdtx_pps_avg tx_bytes    
------------ --------- ---- ---------- ---------- ---------- ------------- --------    
19.08.0-rc4  rxonly    2    20562844   26185128   19733602   0             101137623088
19.08.0-rc4  io        2    18951489   26657834   18058913   12570866      103872709817
19.08.0-rc4  rxonly    4    19655456   19525499   18721939   0             75735695979 
19.08.0-rc4  io        4    17562457   20148140   16767052   13132201      78609964604 
19.08.0-rc4  rxonly    8    19669072   23309207   18802317   0             90368826034 
19.08.0-rc4  io        8    16748627   22459050   16024132   14012761      87169515857 
19.08.0-rc4  rxonly    16   19425347   23209207   18517097   0             89612275390 
19.08.0-rc4  io        16   16599030   23695865   15850767   13859622      92333787092 
    5 DPDK                 PERF-DPDK-SINGLE-CORE-PPS-DS15                                                    PASS                16.69 
dpdk_version test_mode core max_rx_pps tx_pps_avg rx_pps_avg fwdtx_pps_avg tx_bytes    r
                                                                                       x
                                                                                       _
                                                                                       b
                                                                                       y
                                                                                       t
                                                                                       e
                                                                                       s
------------ --------- ---- ---------- ---------- ---------- ------------- --------    -
19.08.0-rc4  rxonly    1    13417814   13148636   12675442   0             51047762372 4
19.08.0-rc4  io        1    10531457   13068933   9829639    9829119       50942466296 3 
    6 DPDK                 PERF-DPDK-MULTICORE-PPS-DS15                                                      PASS                21.25 
dpdk_version test_mode core max_rx_pps tx_pps_avg rx_pps_avg fwdtx_pps_avg tx_bytes    r
                                                                                       x
                                                                                       _
                                                                                       b
                                                                                       y
                                                                                       t
                                                                                       e
                                                                                       s
------------ --------- ---- ---------- ---------- ---------- ------------- --------    -
19.08.0-rc4  rxonly    2    19623150   18862242   17707648   0             72845126707 6
19.08.0-rc4  io        2    15024994   19035567   13323782   12349796      73180352773 5
19.08.0-rc4  rxonly    4    17330458   16940087   16245824   0             65292382329 6
19.08.0-rc4  io        4    17776111   17203798   16447430   13364509      67230827381 6
19.08.0-rc4  rxonly    8    16725225   16351507   15745223   0             63038434390 6
19.08.0-rc4  io        8    16696311   16339460   15818508   14983444      63194591648 6 



[LISAv2 Test Results Summary]
Test Run On           : 08/12/2019 22:07:05
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : latest
Initial Kernel Version: 4.15.0-1052-azure
Final Kernel Version  : 4.15.0-1052-azure
Total Test Cases      : 6 (4 Passed, 1 Failed, 1 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:1:46

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                14.92 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
19.08.0-rc4  txonly    after   3314850       3314851      
19.08.0-rc4  txonly    before  3270433       3270433      
19.08.0-rc4  txonly    during  380459        380458       
19.08.0-rc4  txonly    overall 1985012       1985012 
    2 DPDK                 PERF-DPDK-FWD-PPS-DS15                                                            PASS                15.12 
dpdk_version core tx_pps_avg fwdrx_pps_avg fwdtx_pps_avg rx_pps_avg
------------ ---- ---------- ------------- ------------- ----------
19.08.0-rc4  2    20385372   9609284       9609284       9139193   
19.08.0-rc4  4    16698127   10824469      10824469      10113079  
19.08.0-rc4  8    16678232   11063645      11063641      10151922 
    3 DPDK                 PERF-DPDK-SINGLE-CORE-PPS-DS4                                                     PASS                11.38 
dpdk_version test_mode core max_rx_pps tx_pps_avg rx_pps_avg fwdtx_pps_avg tx_bytes    rx_bytes    fwd_bytes  
------------ --------- ---- ---------- ---------- ---------- ------------- --------    --------    ---------  
19.08.0-rc4  rxonly    1    11576833   11473861   11318582   0             44411849716 44129921815 0          
19.08.0-rc4  io        1    11556246   11475083   11037710   11013061      44866958578 43118384510 43040602775 
    4 DPDK                 PERF-DPDK-MULTICORE-PPS-F32                                                    Aborted                    0 
One or more deployments failed. Unable to Deploy one or more VM's. Exception in Create-ResourceGroupDeployment. Source : Line 533 in script .\Libraries\Azure...
    5 DPDK                 PERF-DPDK-SINGLE-CORE-PPS-DS15                                                    PASS                11.47 
dpdk_version test_mode core max_rx_pps tx_pps_avg rx_pps_avg fwdtx_pps_avg tx_bytes    rx_bytes     [...]

2019-08-13 21:54 UTC, abhimarathe commented
![image](https://user-images.githubusercontent.com/13867573/62980029-433b7100-bdda-11e9-8e94-d0c8bca4d7d2.png)

2019-08-13 21:55 UTC, abhimarathe commented
![image](https://user-images.githubusercontent.com/13867573/62980075-5f3f1280-bdda-11e9-9830-4dae80872bb4.png)

2019-08-13 21:56 UTC, abhimarathe commented
![image](https://user-images.githubusercontent.com/13867573/62980101-73830f80-bdda-11e9-9ed4-5314b59376db.png)

2019-08-13 21:59 UTC, abhimarathe commented on Testscripts/Linux/dpdkSetupAndRunTest.sh
> + DPDK_DIR="dpdk"
Done. 
Thank you!

2019-08-14 11:05 UTC, LiliDeng commented
@abhimarathe what is the reason for abort or fail?

2019-08-14 20:46 UTC, abhimarathe commented
@LiliDeng I'm looking into that. Lisav2 did not generate any error messages and we don't have a 100% repro rate for most of them. One thing I'm sure of is that the abort/fail did not occurre due to this change.

2019-08-15 16:49 UTC, juhlee-microsoft commented
> @LiliDeng I'm looking into that. Lisav2 did not generate any error messages and we don't have a 100% repro rate for most of them. One thing I'm sure of is that the abort/fail did not occurre due to this change.

@abhimarathe if abort/fail is not related to this PR, then please investigate through a new issue.

2019-08-15 16:51 UTC, juhlee-microsoft requested changes

2019-08-15 16:51 UTC, juhlee-microsoft commented on Testscripts/Linux/dpdkSetupAndRunTest.sh
> +	#DPDK_DIR="dpdk-$(echo ${dpdkSrcLink} | grep -Po "(\d+\.)+\d+")"
Remove the commented line

2019-08-15 16:51 UTC, juhlee-microsoft commented on Testscripts/Linux/dpdkSetupAndRunTest.sh
> +	dpdkSrcTar="${dpdkSrcLink##*/}"
98 and 101 are duplicated

2019-08-15 20:22 UTC, abhimarathe commented on Testscripts/Linux/dpdkSetupAndRunTest.sh
> +	#DPDK_DIR="dpdk-$(echo ${dpdkSrcLink} | grep -Po "(\d+\.)+\d+")"
Done

2019-08-15 20:23 UTC, abhimarathe commented on Testscripts/Linux/dpdkSetupAndRunTest.sh
> +	dpdkSrcTar="${dpdkSrcLink##*/}"
Removed duplicated code.

2019-08-15 21:21 UTC, lizzha approved these changes

2019-08-16 02:55 UTC, LiliDeng approved these changes

2019-08-16 05:18 UTC, LiliDeng commented
Ava is doing testing.

2019-08-16 06:55 UTC, LiliDeng commented
@abhimarathe Could you please run this case VERIFY-DPDK-COMPLIANCE? We found that is pass in master branch, failed in your branch.

2019-08-19 22:57 UTC, merged