KDUMP-CRASH-SSH: New Testcase to verify KDUMP over SSH
microsoft/lisa pull request #883
Opened 2020-06-26 23:24 UTC by abhimarathe

1. Added ssh port parameter in wait-ForVMToStartSSH function: To use it for ssh port other than 22
2. Enabled .tar installation for "-CustomKernel" parameter
3. Added new testcase: KDUMP-CRASH-SSH

`[LISAv2 Test Results Summary]
Test Run On           : 06/26/2020 05:08:56
ARM Image Under Test  : OpenLogic : CentOS : 7.7 : latest
Initial Kernel Version: 5.7.0
Final Kernel Version  : 5.7.0
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SSH                                                                   PASS                 6.48 

Logs can be found at C:\LISAv2\VW67\TestResults\2020-06-25-22-08-51-9660`

2020-06-27 08:56 UTC, LiliDeng commented
@abhimarathe Does it need special kernel?

2020-06-30 04:37 UTC, juhlee-microsoft requested changes

2020-06-30 04:37 UTC, juhlee-microsoft commented on Testscripts/Windows/KDUMP-CRASH-SSH.ps1
> +        Run-LinuxCmd -ip $receiverVMData.PublicIP -port $receiverVMData.SSHPort `
Use $TestProvider.RestartAllDeployments()

2020-06-30 04:37 UTC, juhlee-microsoft commented on Testscripts/Windows/KDUMP-CRASH-SSH.ps1
> +        Start-Sleep -Seconds 60
How do you find this '60' seconds? Was it relevant to any VM size?

2020-06-30 04:37 UTC, juhlee-microsoft commented on Libraries/CommonFunctions.psm1
> +        [String] $PortNumber=22,
Your test only uses 2 predefined ports, but why do you add it? They are not 22 even.

2020-06-30 04:37 UTC, juhlee-microsoft commented on Testscripts/Linux/KDUMP-Config.sh
> +    elif [ "$sshIP" ] && [ "$sshIP" != "" ]; then
Does it mean kdump is running over the port 22?

2020-06-30 04:37 UTC, juhlee-microsoft commented on Testscripts/Linux/KDUMP-Config.sh
> +            LogMsg "No module pci_hv"
It looks like a problem or test failure data. Correct?

2020-06-30 04:37 UTC, juhlee-microsoft commented on Testscripts/Linux/KDUMP-Config.sh
> +            LogMsg "No module pci_hv"
LogErr here and above?

2020-06-30 04:37 UTC, juhlee-microsoft commented on Testscripts/Linux/KDUMP-Config.sh
> +        service kexec restart
is it possible not to have this service?

2020-06-30 20:47 UTC, abhimarathe commented on Testscripts/Windows/KDUMP-CRASH-SSH.ps1
> +        Start-Sleep -Seconds 60
Did ask Wei hu about this, he said 20-30 seconds are enough but keeping it 60 seconds to be on safer side.
I don't know if it is relevant to vm size.

2020-07-02 18:05 UTC, abhimarathe commented on Testscripts/Linux/KDUMP-Config.sh
> +    elif [ "$sshIP" ] && [ "$sshIP" != "" ]; then
yes.
Not sure though but as we don't configure SSH port anywhere in the config I assume it is the default one: 22

2020-07-02 18:07 UTC, abhimarathe commented on Libraries/CommonFunctions.psm1
> +        [String] $PortNumber=22,
This is a common function so I thought it would be better to predefined sshport as it is the default one in most of the cases.

2020-07-02 18:09 UTC, abhimarathe commented on Testscripts/Linux/KDUMP-Config.sh
> +            LogMsg "No module pci_hv"
I will confirm with Wei about this. I didn't see any failure.

2020-07-07 02:25 UTC, abhimarathe commented on Testscripts/Linux/KDUMP-Config.sh
> +            LogMsg "No module pci_hv"
Yes.
I will make changes

2020-07-08 00:46 UTC, juhlee-microsoft commented
No update in last 8 days. Are you still working on this PR? Or, plan to close it? @abhimarathe

2020-07-13 03:05 UTC, LiliDeng requested changes

2020-07-13 03:05 UTC, LiliDeng commented on Testscripts/Linux/KDUMP-Config.sh
> +    elif [ "$sshIP" ]; then
if this piece of code is the same for each distro, please put it into a common function, not repeat again and again

2020-07-13 03:05 UTC, LiliDeng commented on Testscripts/Linux/KDUMP-Config.sh
> -        echo "extra_modules ata_piix sr_mod sd_mod" >> /etc/kdump.conf
make sure you didn't loss 'extra_modules'. it is a plain string.

2020-07-15 03:01 UTC, harz566 commented
@abhimarathe Hello, please kindly note, the LISA has been refactored in its xml definition.  Generally, you need to replace <AdditionalHWConfig>  with <SetupConfig>, if you have <AdditionalHWConfig> defined,  otherwise, you need create a new XML Tag <SetupConfig>,  and move any of these xml Tags (<SetupType>, <OverrideVMSize>, <ARMImageName>, <TestLocation>, <Networking>, <DiskType>, <ImageType>, <OSType>, <OsVHD>)  as child element of <SetupConfig>.   Some of those Tags are optional, please reference to the existing xml definition from master branch.   Hope that doesn't bring much inconvenient to you. Thanks!

2020-07-23 18:35 UTC, juhlee-microsoft commented
@abhimarathe Are you working on this PR? It's been open without an update in the last 9 days.

2020-07-23 18:52 UTC, abhimarathe commented
> @abhimarathe Are you working on this PR? It's been open without an update in the last 9 days.

@juhlee-microsoft  Yes, I'm facing some difficulties with ubuntu distro for generating dump. I'm talking to Wei how has developed these patches. I will fix the testcase as soon as I get to know what steps need to be added. That's why I have kept this PR in draft mode.

2020-08-14 06:08 UTC, closed without merging